In [3]:
import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

1 Physical GPUs, 1 Logical GPUs


In [4]:
(x, y), (x_test, y_test) = datasets.cifar10.load_data()

y = tf.squeeze(y, axis=1)
y_test = tf.squeeze(y_test, axis=1)

NameError: name 'datasets' is not defined

-------------------------------------------------------------------------------------


In [4]:
train_db = tf.data.Dataset.from_tensor_slices((x_train, y_train)).shuffle(10000).batch(128)

In [6]:
def preprocess(x, y):
    x = tf.cast(x, tf.float32) / 255.
    x = tf.reshape(x, [-1, 28*28])
    y = tf.cast(y, tf.int32)
    y = tf.one_hot(y, depth=10)
    return x, y

In [ ]:
for epoch in range(20):
    for step, (x, y) in enumerate(train_db):
        # training...

In [13]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

x = tf.random.normal([4, 28*28])
fc = layers.Dense(512, activation='relu')
h1 = fc(x)

In [14]:
fc.kernel

<tf.Variable 'dense_1/kernel:0' shape=(784, 512) dtype=float32, numpy=
array([[-0.06257042, -0.06308032,  0.06167884, ...,  0.05575965,
        -0.00344685, -0.03837156],
       [ 0.04773387, -0.01096474,  0.02275785, ..., -0.02869795,
         0.05242955, -0.05594587],
       [-0.01732337, -0.04400137,  0.02286585, ..., -0.01820702,
        -0.01409402,  0.06144083],
       ...,
       [ 0.01516502,  0.00211865,  0.03488779, ...,  0.05362887,
        -0.03985165, -0.05604403],
       [-0.02082402,  0.01305695,  0.02862246, ...,  0.05900629,
         0.01944529,  0.03969408],
       [ 0.00312306,  0.02058729,  0.05727644, ..., -0.02149379,
         0.00984266,  0.05382003]], dtype=float32)>

In [15]:
fc.bias

<tf.Variable 'dense_1/bias:0' shape=(512,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 

In [16]:
fc.trainable_variables

[<tf.Variable 'dense_1/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[-0.06257042, -0.06308032,  0.06167884, ...,  0.05575965,
         -0.00344685, -0.03837156],
        [ 0.04773387, -0.01096474,  0.02275785, ..., -0.02869795,
          0.05242955, -0.05594587],
        [-0.01732337, -0.04400137,  0.02286585, ..., -0.01820702,
         -0.01409402,  0.06144083],
        ...,
        [ 0.01516502,  0.00211865,  0.03488779, ...,  0.05362887,
         -0.03985165, -0.05604403],
        [-0.02082402,  0.01305695,  0.02862246, ...,  0.05900629,
          0.01944529,  0.03969408],
        [ 0.00312306,  0.02058729,  0.05727644, ..., -0.02149379,
          0.00984266,  0.05382003]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(512,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [17]:
fc.non_trainable_variables

[]

In [19]:
fc.weights

[<tf.Variable 'dense_1/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[-0.06257042, -0.06308032,  0.06167884, ...,  0.05575965,
         -0.00344685, -0.03837156],
        [ 0.04773387, -0.01096474,  0.02275785, ..., -0.02869795,
          0.05242955, -0.05594587],
        [-0.01732337, -0.04400137,  0.02286585, ..., -0.01820702,
         -0.01409402,  0.06144083],
        ...,
        [ 0.01516502,  0.00211865,  0.03488779, ...,  0.05362887,
         -0.03985165, -0.05604403],
        [-0.02082402,  0.01305695,  0.02862246, ...,  0.05900629,
          0.01944529,  0.03969408],
        [ 0.00312306,  0.02058729,  0.05727644, ..., -0.02149379,
          0.00984266,  0.05382003]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(512,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [20]:
fc.variable_dtype

'float32'

In [21]:
fc.variables

[<tf.Variable 'dense_1/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[-0.06257042, -0.06308032,  0.06167884, ...,  0.05575965,
         -0.00344685, -0.03837156],
        [ 0.04773387, -0.01096474,  0.02275785, ..., -0.02869795,
          0.05242955, -0.05594587],
        [-0.01732337, -0.04400137,  0.02286585, ..., -0.01820702,
         -0.01409402,  0.06144083],
        ...,
        [ 0.01516502,  0.00211865,  0.03488779, ...,  0.05362887,
         -0.03985165, -0.05604403],
        [-0.02082402,  0.01305695,  0.02862246, ...,  0.05900629,
          0.01944529,  0.03969408],
        [ 0.00312306,  0.02058729,  0.05727644, ..., -0.02149379,
          0.00984266,  0.05382003]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(512,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [22]:
from tensorflow.keras import Sequential, layers

In [23]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def derivative_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

In [24]:
network = Sequential([layers.Dense(256, activation='relu'),
                      layers.Dense(128, activation='relu'),
                      layers.Dense(64, activation='relu'),
                      layers.Dense(32, activation='relu'),
                      layers.Dense(10)])

network.build(input_shape=(4, 28*28))
network.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (4, 256)                  200960    
                                                                 
 dense_3 (Dense)             (4, 128)                  32896     
                                                                 
 dense_4 (Dense)             (4, 64)                   8256      
                                                                 
 dense_5 (Dense)             (4, 32)                   2080      
                                                                 
 dense_6 (Dense)             (4, 10)                   330       
                                                                 
Total params: 244,522
Trainable params: 244,522
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import tensorflow as tf